# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('idstory', models.AutoField(primary_key=True, serialize=False)),
                ('parts', models.IntegerField()),
                ('closed', models.CharField(max_length=1)),
                ('rating', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('nextusertype', models.CharField(max_length=1)),
                ('nextuser', models.CharField(blank=True, max_length=45, null=True)),
                ('waittime', models.IntegerField()),
                ('maxparts', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('started', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'stories',
                'db_table': 'storychain',
                'verbose_name': 'story',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storyparts',
            fields=[
                ('idstoryparts', models.AutoField(primary_key=True, serialize=False)),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'storyparts',
                'db_table': 'storyparts',
                'verbose_name': 'storypart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idusers', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('karma', models.IntegerField()),
                ('paidtill', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'verbose_name': 'user',
                'managed': False,
            },
        ),
    ]
