# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('idstory', models.AutoField(primary_key=True, serialize=False)),
                ('parts', models.IntegerField()),
                ('closed', models.CharField(max_length=1)),
                ('rating', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('nextusertype', models.CharField(max_length=1)),
                ('nextuser', models.CharField(blank=True, max_length=45, null=True)),
                ('waittime', models.IntegerField()),
                ('maxparts', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('started', models.DateTimeField()),
            ],
            options={
                'db_table': 'story',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Storyparts',
            fields=[
                ('idstoryparts', models.AutoField(primary_key=True, serialize=False)),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'storyparts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idusers', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('karma', models.IntegerField()),
                ('paidtill', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='storyparts',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='ongames.Users'),
        ),
        migrations.AddField(
            model_name='story',
            name='creator',
            field=models.ForeignKey(db_column='creator', on_delete=django.db.models.deletion.DO_NOTHING, to='ongames.Users'),
        ),
    ]
