# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ongames', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'managed': True, 'verbose_name': 'story', 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterModelOptions(
            name='storyparts',
            options={'managed': True, 'verbose_name': 'storypart', 'verbose_name_plural': 'storyparts'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
